In [2]:
import tensorflow as tf
import time

In [5]:
matrix_1 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]],name="mat1")
matrix_2 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]],name="mat2")

In [6]:
scalar = tf.constant(5)
number = tf.Variable(1,name = "counter")

In [8]:
add_msg = tf.constant("\nRusult of matrix addition\n")
mul_msg = tf.constant("\nRusult of matrix multiplication\n")
scalar_mul_msg = tf.constant("\nResult of scalar multiplication\n")
number_mul_msg = tf.constant("\nResult of Number multiplication\n")

In [10]:
mat_add = tf.add(matrix_1,matrix_2)
mat_mul = tf.matmul(matrix_1,matrix_2)
mat_scalar_mul = tf.multiply(scalar,mat_mul)
mat_number_mul = tf.multiply(number,mat_mul)

In [12]:
init_op = tf.global_variables_initializer()
sess = tf.Session()
tf.device("/cpu:0")
sess.run(init_op)

In [14]:
for i in range(1,100):
    print "\nFor i =",i
    
    print(sess.run(add_msg))
    print(sess.run(mat_add))
    
    print(sess.run(mul_msg))
    print(sess.run(mat_mul))
    
    print(sess.run(scalar_mul_msg))
    print(sess.run(mat_scalar_mul))
    
    update = tf.assign(number,tf.constant(i))
    sess.run(update)
    print(sess.run(number_mul_msg))
    print(sess.run(mat_number_mul))
    
    time


For i = 1

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

For i = 2

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 60  72  84]
 [132 162 192]
 [204 252 300]]

For i = 3

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 90 108 126]
 [198 243 288]
 [306 378 450]]

For i = 4

Rusult of matrix addition

[[ 2  4  6]
 


Result of Number multiplication

[[1020 1224 1428]
 [2244 2754 3264]
 [3468 4284 5100]]

For i = 35

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[1050 1260 1470]
 [2310 2835 3360]
 [3570 4410 5250]]

For i = 36

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[1080 1296 1512]
 [2376 2916 3456]
 [3672 4536 5400]]

For i = 37

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number mult

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 2010  2412  2814]
 [ 4422  5427  6432]
 [ 6834  8442 10050]]

For i = 68

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 2040  2448  2856]
 [ 4488  5508  6528]
 [ 6936  8568 10200]]

For i = 69

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplication

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Result of scalar multiplication

[[150 180 210]
 [330 405 480]
 [510 630 750]]

Result of Number multiplication

[[ 2070  2484  2898]
 [ 4554  5589  6624]
 [ 7038  8694 10350]]

For i = 70

Rusult of matrix addition

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Rusult of matrix multiplicat


Result of Number multiplication

[[ 2970  3564  4158]
 [ 6534  8019  9504]
 [10098 12474 14850]]
